# 开发环境配置
# =============================================
# 此文件为Spring Boot应用的开发环境专用配置文件，当spring.profiles.active=dev时生效
# 主要用于覆盖主配置文件(application.yml)中的设置，提供适合开发调试的配置选项
# 开发环境配置特点：详细日志、禁用缓存、启用调试功能、宽松的安全设置等

spring:  # Spring Boot开发环境配置节点
  # 开发工具配置 - Spring Boot DevTools相关设置
  devtools:
    restart:  # 自动重启配置，代码修改后自动重启应用
      enabled: true  # 启用自动重启功能，提高开发效率
      additional-paths: src/main/java,src/main/resources  # 监控的额外路径，这些路径下文件变化会触发重启
      exclude: static/**,templates/**  # 排除的路径，静态资源和模板文件变化不触发重启，避免频繁重启
    livereload:  # 实时重载配置，浏览器自动刷新功能
      enabled: true  # 启用LiveReload功能，配合浏览器插件可实现页面自动刷新
  
  # JPA开发环境配置 - 数据库访问层开发设置
  jpa:
    show-sql: true  # 开发环境显示SQL语句，便于调试和优化SQL
    properties:  # Hibernate开发环境属性
      hibernate:
        format_sql: true  # 格式化SQL输出，使SQL语句更易读
        use_sql_comments: true  # 在SQL中显示注释，帮助理解SQL用途和来源
  
  # Thymeleaf开发环境配置 - 模板引擎开发设置
  thymeleaf:
    cache: false  # 开发环境禁用模板缓存，模板修改后立即生效，无需重启
  
  # H2控制台配置 - 内嵌数据库管理工具（当前项目使用MySQL，此配置暂时禁用）
  h2:
    console:
      enabled: false  # 禁用H2控制台，因为项目使用MySQL数据库

# 日志开发环境配置 - 开发阶段的详细日志设置
logging:
  level:  # 开发环境日志级别配置，比生产环境更详细
    com.example.oauth2sso: DEBUG  # 应用包设为DEBUG级别，输出详细的调试信息
    org.springframework.security: DEBUG  # Spring Security调试级别，便于排查认证授权问题
    org.springframework.security.oauth2: DEBUG  # OAuth2组件调试级别，详细记录OAuth2流程
    org.springframework.web: DEBUG  # Spring Web组件调试级别，记录请求处理详情
    org.hibernate.SQL: DEBUG  # Hibernate SQL调试级别，显示所有SQL语句
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 参数绑定跟踪级别，显示SQL参数值
    root: INFO  # 根日志记录器保持INFO级别，避免第三方库产生过多日志

# 开发环境应用配置 - 项目开发阶段的特殊业务配置
app:
  # 开发模式标识
  debug: true  # 开发调试模式标志，可在代码中判断是否为开发环境
  
  # OAuth2开发环境配置 - 认证相关的开发设置
  oauth2:
    # 开发环境可以使用测试回调URL，支持localhost回调
    test-mode: true  # 测试模式标志，可启用一些仅在开发环境使用的功能
    
  # 安全开发环境配置 - 适合开发调试的安全设置
  security:
    # 开发环境会话超时时间较长，避免频繁重新登录影响开发效率
    session-timeout: 7200  # 会话超时时间设为2小时(7200秒)，比生产环境的1小时更长 